'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace CustomDraw


	Partial Public Class _Default

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' gaugeControl control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected gaugeControl As Global.DevExpress.Web.ASPxGauges.ASPxGaugeControl

		''' <summary>
		''' arcScale control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected arcScale As Global.DevExpress.Web.ASPxGauges.Gauges.Circular.ArcScaleComponent

		''' <summary>
		''' arcScaleBackgroundLayer control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected arcScaleBackgroundLayer As Global.DevExpress.Web.ASPxGauges.Gauges.Circular.ArcScaleBackgroundLayerComponent

		''' <summary>
		''' arcScaleNeedle control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected arcScaleNeedle As Global.DevExpress.Web.ASPxGauges.Gauges.Circular.ArcScaleNeedleComponent

		''' <summary>
		''' ASPxCheckBox1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected ASPxCheckBox1 As Global.DevExpress.Web.ASPxEditors.ASPxCheckBox

		''' <summary>
		''' value control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected value As Global.DevExpress.Web.ASPxEditors.ASPxSpinEdit
	End Class
End Namespace
